routes/web.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

Route::resource('clientes', 'ClientController')->middleware('auth');

Route::resource('productos', 'ProductController')->middleware('auth');

Route::resource('cotizaciones', 'QuotationController')->middleware('auth');

Route::resource('roles', 'RoleController')->middleware('auth');

Route::get('agregarproductos/{id}', 'AddProductQuotation@add')->name('addproduct')->middleware('auth');
Route::get('forvue/{id}', 'AddProductQuotation@useByVue')->middleware('auth');
Route::post('agregarproductos/{id}', 'AddProductQuotation@store')->name('storeproduct')->middleware('auth');
Route::post('quitarproductos/{id}', 'AddProductQuotation@delete')->name('deleteproduct')->middleware('auth');




//rutas de configuracion de sistema 

Route::get('configuracion', 'ConfigController@index')->name('configuracion.index')->middleware('auth');
Route::get('configuracion/{empresa}', 'ConfigController@edit')->name('configuracion.edit')->middleware('auth');
Route::put('configuracion/{empresa}', 'ConfigController@update')->name('configuracion.update')->middleware('auth');

//usuarios del sistema
Route::get('perfil/{id}', 'UserController@perfil')->name('perfil')->middleware('auth');
Route::get('usuarios', 'UserController@index')->name('usuarios.index')->middleware('auth', 'permission:usuarios.index');
Route::get('usuarios/create', 'UserController@create')->name('usuarios.create')->middleware('auth');
Route::post('usuarios', 'UserController@store')->name('usuarios.store')->middleware('auth');
Route::get('usuarios/{id}/edit', 'UserController@edit')->name('usuarios.edit')->middleware('auth');
Route::put('usuarios/{id}', 'UserController@update')->name('usuarios.update')->middleware('auth');
Route::delete('usuarios/{id}', 'UserController@delete')->name('usuarios.delete')->middleware('auth');
//cambiar contraseña
Route::get('usuarios/{id}/cambiar-contraseña', 'UserController@editPass')->name('edit.password')->middleware('auth');
Route::put('usuarios-update/{id}', 'UserController@updatePass')->name('update.password')->middleware('auth');


Route::get('empresa', 'RecursosAccesibles@getData');

Route::get('addproductsvue/{id}', 'AddProductQuotation@getProducts');

resources/views/clientes/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                            <a href="{{route('clientes.index')}}" class="btn btn-primary btn-sm">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                        Nuevo Cliente
                    </div>
                </div>
                
                <div class="card-body">
                        <form class="form-horizontal" method="POST" action="{{route('clientes.store')}}">
                            @csrf
                                <fieldset>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="textinput">Nombre</label>  
                                  <div class="col-md-12">
                                  <input id="textinput" name="name" type="text" placeholder="" class="form-control input-md">
                                  {!!$errors->first('name', '<b class="text-danger">:message</b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="email">Email</label>  
                                  <div class="col-md-12">
                                  <input id="email" name="email" type="email" placeholder="" class="form-control input-md">
                                  {!!$errors->first('email', '<b class="text-danger">:message</b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="phone">Teléfono</label>  
                                  <div class="col-md-12">
                                  <input id="phone" name="phone" type="text" placeholder="" class="form-control input-md">
                                  {!!$errors->first('phone', '<b class="text-danger">:message</b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="address">Dirección</label>  
                                  <div class="col-md-12">
                                  <input id="address" name="address" type="text" placeholder="" class="form-control input-md">
                                  {!!$errors->first('address', '<b class="text-danger">:message</b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Button -->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for=""></label>
                                  <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                  </div>
                                </div>
                                
                                </fieldset>
                                </form>
                                
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clientes/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                            <a href="{{route('clientes.index')}}" class="btn btn-primary btn-sm">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                        Editar Cliente
                    </div>
                </div>
                
                <div class="card-body">
                        <form class="form-horizontal" method="POST" action="{{route('clientes.update', $cliente->id)}}">
                            @csrf
                            @method('PUT')
                                <fieldset>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="textinput">Nombre</label>  
                                  <div class="col-md-12">
                                  <input id="textinput" name="name" type="text" placeholder="" class="form-control input-md" value="{{$cliente->name}}">
                                  {!!$errors->first('name', '<b class="text-danger">:message</b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="email">Email</label>  
                                  <div class="col-md-12">
                                  <input id="email" name="email" type="email" placeholder="" class="form-control input-md" value="{{$cliente->email}}">
                                  {!!$errors->first('email', '<b class="text-danger">:message</b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="phone">Teléfono</label>  
                                  <div class="col-md-12">
                                  <input id="phone" name="phone" type="text" placeholder="" class="form-control input-md" value="{{$cliente->phone}}">
                                  {!!$errors->first('phone', '<b class="text-danger">:message</b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="address">Dirección</label>  
                                  <div class="col-md-12">
                                  <input id="address" name="address" type="text" placeholder="" class="form-control input-md" value="{{$cliente->address}}">
                                  {!!$errors->first('address', '<b class="text-danger">:message</b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Button -->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for=""></label>
                                  <div class="col-md-12">
                                    <button id="" name="" class="btn btn-primary">Actualizar</button>
                                  </div>
                                </div>
                                
                                </fieldset>
                                </form>
                                
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                        Clientes
                        <a href="{{route('clientes.create')}}" class="btn btn-primary btn-sm float-right">
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
                
                <div class="card-body">
                    <div class="table-responsive">
                    <table class="table table-hover table-sm">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Correo Electrónico</th>
                                <th>Teléfono</th>
                                <th>Dirección</th>
                                <th><center>Editar</center></th>
                                <th><center>Eliminar</center></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($clientes as $cliente)
                                <tr>
                                    <td>{{$cliente->id}}</td>
                                    <td>{{$cliente->name}}</td>
                                    <td>{{$cliente->email}}</td>
                                    <td>{{$cliente->phone}}</td>
                                    <td>{{$cliente->address}}</td>
                                    <td>
                                        <center>
                                        <a href="{{route('clientes.edit', $cliente->id)}}" class="btn btn-warning btn-sm">
                                            <i class="fa fa-pencil" aria-hidden="true"></i>
                                        </a>
                                        </center>
                                    </td>
                                    <td>
                                        <center>
                                        <form action="{{route('clientes.destroy', $cliente->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('¿Estas Seguro de eliminar el cliente?')">
                                                    <i class="fa fa-window-close" aria-hidden="true"></i>
                                            </button>
                                        </form>
                                        </center>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection