routes/web.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

Route::resource('clientes', 'ClientController')->middleware('auth');

Route::resource('productos', 'ProductController')->middleware('auth');

Route::resource('cotizaciones', 'QuotationController')->middleware('auth');

Route::resource('roles', 'RoleController')->middleware('auth');

Route::get('agregarproductos/{id}', 'AddProductQuotation@add')->name('addproduct')->middleware('auth');
Route::get('forvue/{id}', 'AddProductQuotation@useByVue')->middleware('auth');
Route::post('agregarproductos/{id}', 'AddProductQuotation@store')->name('storeproduct')->middleware('auth');
Route::post('quitarproductos/{id}', 'AddProductQuotation@delete')->name('deleteproduct')->middleware('auth');




//rutas de configuracion de sistema 

Route::get('configuracion', 'ConfigController@index')->name('configuracion.index')->middleware('auth');
Route::get('configuracion/{empresa}', 'ConfigController@edit')->name('configuracion.edit')->middleware('auth');
Route::put('configuracion/{empresa}', 'ConfigController@update')->name('configuracion.update')->middleware('auth');

//usuarios del sistema
Route::get('perfil/{id}', 'UserController@perfil')->name('perfil')->middleware('auth');
Route::get('usuarios', 'UserController@index')->name('usuarios.index')->middleware('auth', 'permission:usuarios.index');
Route::get('usuarios/create', 'UserController@create')->name('usuarios.create')->middleware('auth');
Route::post('usuarios', 'UserController@store')->name('usuarios.store')->middleware('auth');
Route::get('usuarios/{id}/edit', 'UserController@edit')->name('usuarios.edit')->middleware('auth');
Route::put('usuarios/{id}', 'UserController@update')->name('usuarios.update')->middleware('auth');
Route::delete('usuarios/{id}', 'UserController@delete')->name('usuarios.delete')->middleware('auth');
//cambiar contraseña
Route::get('usuarios/{id}/cambiar-contraseña', 'UserController@editPass')->name('edit.password')->middleware('auth');
Route::put('usuarios-update/{id}', 'UserController@updatePass')->name('update.password')->middleware('auth');


Route::get('empresa', 'RecursosAccesibles@getData');

Route::get('addproductsvue/{id}', 'AddProductQuotation@getProducts');

resources/views/productos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                            <a href="{{route('productos.index')}}" class="btn btn-primary btn-sm">
                                    <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                        Nuevo Producto
                    </div>
                </div>
                
                <div class="card-body">
                        <form class="form-horizontal" method="POST" action="{{route('productos.store')}}" enctype="multipart/form-data">
                               @csrf
                                <!-- File Button --> 
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="file">Imagen</label>
                                  <div class="col-md-4">
                                    <input id="file" name="file" class="input-file" type="file">
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="name">Nombre</label>  
                                  <div class="col-md-12">
                                  <input id="name" name="name" type="text" placeholder="" class="form-control input-md" value="{{old('name')}}">
                                  {!!$errors->first('name', '<b class="text-danger">:message<b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="code">Código</label>  
                                  <div class="col-md-12">
                                  <input id="code" name="cod" type="text" placeholder="" class="form-control input-md" value="{{old('cod')}}">
                                  {!!$errors->first('cod', '<b class="text-danger">:message<b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="stock">Cantidad</label>  
                                  <div class="col-md-12">
                                  <input id="stock" name="stock" type="text" placeholder="" class="form-control input-md" value="{{old('stock')}}">
                                  {!!$errors->first('stock', '<b class="text-danger">:message<b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="price">Precio</label>  
                                  <div class="col-md-12">
                                  <input id="price" name="price" type="text" placeholder="" class="form-control input-md" value="{{old('price')}}">
                                  {!!$errors->first('price', '<b class="text-danger">:message<b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Button -->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for=""></label>
                                  <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                  </div>
                                </div>
                                
                                </fieldset>
                                </form>
                                
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/productos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                            <a href="{{route('productos.index')}}" class="btn btn-primary btn-sm">
                                    <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                        Editar Producto
                    </div>
                </div>
                
                <div class="card-body">
                        <form class="form-horizontal" method="POST" action="{{route('productos.update', $producto->id)}}" enctype="multipart/form-data">
                               @csrf
                               @method('PUT')
                                <!-- File Button --> 
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="file">Imagen</label>
                                  <div class="col-md-4">
                                    <input id="file" name="file" class="input-file" type="file" value="{{$producto->file}}"><hr>
                                    <img src="{{Storage::url($producto->file)}}" width="150px" height="150px">
                                  </div>
                                 
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="name">Nombre</label>  
                                  <div class="col-md-12">
                                  <input id="name" name="name" type="text" placeholder="" class="form-control input-md" value="{{$producto->name}}">
                                  {!!$errors->first('name', '<b class="text-danger">:message<b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="code">Código</label>  
                                  <div class="col-md-12">
                                  <input id="code" name="cod" type="text" placeholder="" class="form-control input-md" value="{{$producto->cod}}">
                                  {!!$errors->first('cod', '<b class="text-danger">:message<b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="stock">Cantidad</label>  
                                  <div class="col-md-12">
                                  <input id="stock" name="stock" type="text" placeholder="" class="form-control input-md" value="{{$producto->stock}}">
                                  {!!$errors->first('stock', '<b class="text-danger">:message<b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for="price">Precio</label>  
                                  <div class="col-md-12">
                                  <input id="price" name="price" type="text" placeholder="" class="form-control input-md" value="{{$producto->price}}">
                                  {!!$errors->first('price', '<b class="text-danger">:message<b>')!!}
                                  </div>
                                </div>
                                
                                <!-- Button -->
                                <div class="form-group">
                                  <label class="col-md-4 control-label" for=""></label>
                                  <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary">Actualizar</button>
                                  </div>
                                </div>
                                
                                </fieldset>
                                </form>
                                
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/productos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                        Productos
                        <a href="{{route('productos.create')}}" class="btn btn-primary btn-sm float-right">
                                <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
                
                <div class="card-body">
                    <div class="table-responsive">
                    <table class="table tabla-hover table-sm">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Imagen</th>
                                <th>Nombre</th>
                                <th>Código</th>
                                <th>Cantidad</th>
                                <th>Precio</th>
                                <th><center>Editar</center></th>
                                <th><center>Eliminar</center></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($productos as $producto)
                                <tr>
                                    <td>{{$producto->id}}</td>
                                    <td>
                                        <img src="{{Storage::url($producto->file)}}" width="50px" height="50px">
                                    </td>
                                    <td>{{$producto->name}}</td>
                                    <td>{{$producto->cod}}</td>
                                    <td>{{$producto->stock}}</td>
                                    <td>{{$producto->price}}</td>
                                    <td>
                                            <center>
                                                <a href="{{route('productos.edit', $producto->id)}}" class="btn btn-warning btn-sm">
                                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                                </a>
                                            </center>
                                    </td>
                                    <td>
                                        <center>
                                            <form action="{{route('productos.destroy', $producto->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('¿Estas Seguro de eliminar el producto?')">
                                                        <i class="fa fa-window-close" aria-hidden="true"></i>
                                                </button>
                                            </form>
                                            </center>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection