routes/web.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

Route::resource('clientes', 'ClientController')->middleware('auth');

Route::resource('productos', 'ProductController')->middleware('auth');

Route::resource('cotizaciones', 'QuotationController')->middleware('auth');

Route::resource('roles', 'RoleController')->middleware('auth');

Route::get('agregarproductos/{id}', 'AddProductQuotation@add')->name('addproduct')->middleware('auth');
Route::get('forvue/{id}', 'AddProductQuotation@useByVue')->middleware('auth');
Route::post('agregarproductos/{id}', 'AddProductQuotation@store')->name('storeproduct')->middleware('auth');
Route::post('quitarproductos/{id}', 'AddProductQuotation@delete')->name('deleteproduct')->middleware('auth');




//rutas de configuracion de sistema 

Route::get('configuracion', 'ConfigController@index')->name('configuracion.index')->middleware('auth');
Route::get('configuracion/{empresa}', 'ConfigController@edit')->name('configuracion.edit')->middleware('auth');
Route::put('configuracion/{empresa}', 'ConfigController@update')->name('configuracion.update')->middleware('auth');

//usuarios del sistema
Route::get('perfil/{id}', 'UserController@perfil')->name('perfil')->middleware('auth');
Route::get('usuarios', 'UserController@index')->name('usuarios.index')->middleware('auth', 'permission:usuarios.index');
Route::get('usuarios/create', 'UserController@create')->name('usuarios.create')->middleware('auth');
Route::post('usuarios', 'UserController@store')->name('usuarios.store')->middleware('auth');
Route::get('usuarios/{id}/edit', 'UserController@edit')->name('usuarios.edit')->middleware('auth');
Route::put('usuarios/{id}', 'UserController@update')->name('usuarios.update')->middleware('auth');
Route::delete('usuarios/{id}', 'UserController@delete')->name('usuarios.delete')->middleware('auth');
//cambiar contraseña
Route::get('usuarios/{id}/cambiar-contraseña', 'UserController@editPass')->name('edit.password')->middleware('auth');
Route::put('usuarios-update/{id}', 'UserController@updatePass')->name('update.password')->middleware('auth');


Route::get('empresa', 'RecursosAccesibles@getData');

Route::get('addproductsvue/{id}', 'AddProductQuotation@getProducts');

resources/views/cotizaciones/add.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    @php
        use App\Http\Controllers\RecursosAccesibles;
        $balboa =  RecursosAccesibles::getData();
    @endphp
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                            <a href="{{route('cotizaciones.index')}}" class="btn btn-primary btn-sm">
                                    <i class="fa fa-arrow-left" aria-hidden="true"></i>
                                </a>
                        Cliente: {{$cotizacion->cliente->name}}
                    </div>
                </div>
                
                <div class="card-body">
                   <form method="POST" action="{{route('cotizaciones.update', $cotizacion->id)}}">
                    @csrf
                    @method('PUT')
                        <fieldset>
                    
                
                <div class="form-group">
                        <label class="col-md-4 control-label" for="textinput">Forma de Pago</label>  
                        <div class="col-md-12">
                                <select id="c" name="waytopay" class="form-control input-md" {{auth()->user()->can('cotizaciones.edit') ? '' : 'disabled'}}>
                                        <option value="">Selecciona una forma de pago</option>
                                        <option value="efectivo" {{$cotizacion->waytopay === 'efectivo' ? 'selected' : ''}}>Efectivo</option>
                                        <option value="tarjeta de credito" {{$cotizacion->waytopay === 'tarjeta de credito' ? 'selected' : ''}}>Tarjeta de Crédito</option>
                                        <option value="cheque" {{$cotizacion->waytopay === 'cheque' ? 'selected' : ''}}>Cheque</option>
                                        
                                </select>
                        
                        </div>
                    </div>
                    <div class="form-group">
                            <label class="col-md-4 control-label" for="textinput">Fecha de Vencimiento</label>  
                            <div class="col-md-12">
                                <input type="date" class="form-control input-md" name="fecha_vencimiento" value="{{$cotizacion->fecha_vencimiento->format('Y-m-d')}}" {{auth()->user()->can('cotizaciones.edit') ? '' : 'disabled'}}>
                            </div>
                        </div>
    
                   @can('cotizaciones.edit')
                        <!-- Button -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for=""></label>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary">Modificar</button>
                        </div>
                      </div>
                   @endcan
                        </fieldset>
                   </form>
                </div>
            </div>
        </div>
    </div>
</div>
<products-quotation id="{{$cotizacion->id}}"></products-quotation>
<add-products-quotation id="{{$cotizacion->id}}"></add-products-quotation>
{{--<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                        Productos Agregados
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                    <table class="table table-hover table-sm">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Código</th>
                                <th>Precio</th>
                                <th>Quitar</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($cotizacion->products as $item)
                                <tr>
                                    <td>{{$item->name}}</td>
                                    <td>{{$item->cod}}</td>
                                    <td>{{$balboa->moneda}}{{$item->price}}</td>
                                    <td>
                                      <form action="{{route('deleteproduct', $item->pivot->id)}}" method="POST">
                                        @csrf
                                        <input type="text" name="cotizacion_id" value="{{$cotizacion->id}}" hidden>
                                        <input type="text" name="price" value="{{$item->price}}" hidden>
                                        <button class="btn btn-danger btn-sm" type="submit">
                                            
                                            <i class="fa fa-window-close" aria-hidden="true"></i>
                                        </button>
                                      </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    </div>
                    <label for="">Sub-Total</label>({{$balboa->moneda}})
                    <input type="text" value="{{$cotizacion->subtotal}}" disabled>
                    <label for="">ITBMS</label>({{$balboa->moneda}})
                    <input type="text" value="{{$cotizacion->itbms}}" disabled>
                    <label for="">Total</label>({{$balboa->moneda}})
                    <input type="text" value="{{$cotizacion->total}}" disabled>
                    
                </div>
              
            </div>
        </div>
    </div>
</div>--}}


{{--<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                        Agregar Productos
                    </div>
                </div>
                
                <div class="card-body">
                    <form action="{{route('storeproduct', $cotizacion->id)}}" method="POST">
                        @csrf
                        
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="textinput">Productos</label>  
                            <div class="col-md-12">
                                    <select id="addproduct" name="product_id" class="form-control input-md">
                                            <option value="">Buscar Productos</option>
                                            @foreach ($productos as $producto)
                                            <option value="{{$producto->id}}">{{$producto->name}}</option>
                                            @endforeach
                                    </select>
                                    {!!$errors->first('product_id', '<b class="text-danger">:message</b>')!!}
                            </div>
                            
                        </div>
                        
                        <!-- Button -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for=""></label>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary">Agregar</button>
                        </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
--}}
@endsection

resources/views/cotizaciones/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                            <a href="{{route('cotizaciones.index')}}" class="btn btn-primary btn-sm">
                                    <i class="fa fa-arrow-left" aria-hidden="true"></i>
                                </a>
                        Nueva Cotización
                    </div>
                </div>
                <div class="card-body">
                <form class="form-horizontal" method="POST" action="{{route('cotizaciones.store')}}">
                    @csrf
                    <fieldset>
                        
                    
                    <!-- Text input-->
            <div class="form-group">
                <label class="col-md-4 control-label" for="textinput">Cliente</label>  
                <div class="col-md-12">
                        <select id="c" name="client_id" class="form-control input-md">
                                <option value="">Selecciona un cliente</option>
                                @foreach ($clientes as $cliente)
                                <option value="{{$cliente->id}}">{{$cliente->name}}</option>
                                @endforeach
                        </select>
                
                </div>
            </div>
            <div class="form-group">
                    <label class="col-md-4 control-label" for="textinput">Forma de Pago</label>  
                    <div class="col-md-12">
                            <select id="c" name="waytopay" class="form-control input-md">
                                    <option value="">Selecciona una forma de pago</option>
                                    <option value="efectivo">Efectivo</option>
                                    <option value="tarjeta de credito">Tarjeta de Crédito</option>
                                    <option value="cheque">Cheque</option>
                                    
                            </select>
                    
                    </div>
                </div>
                <div class="form-group">
                        <label class="col-md-4 control-label" for="textinput">Fecha de Vencimiento</label>  
                        <div class="col-md-12">
                            <input type="date" class="form-control input-md" name="fecha_vencimiento">
                        </div>
                    </div>

                <!-- Button -->
                <div class="form-group">
                        <label class="col-md-4 control-label" for=""></label>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary">Guardar</button>
                        </div>
                      </div>
                    </fieldset>
                </form>
                                
                </div>   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/cotizaciones/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                        Cotizaciones
                        @can('cotizaciones.create')
                            <a href="{{route('cotizaciones.create')}}" class="btn btn-primary btn-sm float-right">
                                <i class="fa fa-plus" aria-hidden="true"></i>
                            </a>
                        @endcan
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                    <table class="table table-hover table-sm">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Cliente</th>
                                <th>Vendedor</th>
                                <th>Forma de Pago</th>
                                <th>Cantidad</th>
                                <th>Total</th>
                                <th>Creación</th>
                                <th>Vencimiento</th>
                                @can('addproduct')
                                <th><center>Agregar/Quitar</center></th>
                                @endcan
                                @can('cotizaciones.show')
                                <th><center>Ver/Dercargar</center></th>
                                @endcan
                                @can('cotizaciones.destroy')
                                <th><center>Eliminar</center></th>
                                @endcan
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($cotizaciones as $cotizacion)
                                <tr>
                                    <td>{{$cotizacion->id}}</td>
                                    <td>{{$cotizacion->cliente->name}}</td>
                                    <td>{{$cotizacion->seller->name}}</td>
                                    <td>{{$cotizacion->waytopay}}</td>
                                    <td><center>{{$cotizacion->products->count()}}</center></td>
                                    <td>{{$cotizacion->total}}</td>
                                    <td>{{$cotizacion->created_at->format('d-m-Y')}}</td>
                                    <td>{{$cotizacion->fecha_vencimiento->format('d-m-Y')}}</td>
                                    @can('addproduct')
                                    <td>
                                        <center>
                                            <a href="{{route('addproduct', $cotizacion->id)}}" class="btn btn-primary btn-sm">
                                                    <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                            </a>
                                        </center>
                                    </td>
                                    @endcan
                                    @can('cotizaciones.show')
                                    <td>
                                        <center>
                                            <a href="{{route('cotizaciones.show', $cotizacion->id)}}" target="_blank" class="btn btn-primary btn-sm">
                                                    <i class="fa fa-download" aria-hidden="true"></i>
                                            </a>
                                        </center>
                                    </td>
                                    @endcan
                                    @can('cotizaciones.destroy')
                                    <td>
                                        <center>
                                            <form action="{{route('cotizaciones.destroy', $cotizacion->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('¿Estas Seguro de eliminar el cliente?')">
                                                        <i class="fa fa-window-close" aria-hidden="true"></i>
                                                </button>
                                            </form>
                                            </center>
                                    </td>
                                    @endcan
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/cotizaciones/pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Cotización</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
	<style>
		.cuadro{
			width: 100%;
			border: 1px solid black;
			margin-bottom: 1%;
			padding: 10px;
			border-radius: 5px;
		}
	</style>
</head>
<body>
		<div class="container->fluid">
				<div class="row">
						<div class="col-sm-12">
							<strong><center><h2>{{$empresa->company_name}}</h2></center></strong>
							<label class="text-secondary"><center>R.U.C. {{$empresa->ruc}}</center></label>
						</div>
						
				</div>
				<div class="cuadro">
						<p><strong>Teléfono: </strong>{{$empresa->telephone}}</p>
						<p><strong>Dirección: </strong>{{$empresa->address}}</p>
						<p><strong>Email: </strong>{{$empresa->email}}</p>
				</div>
		</div>
	
		<div class="row">
			<div class="col-sm-12">
				<table class="table table-sm table-bordered">
					<thead>
						<tr class="table-primary">
							<th>Cliente</th>
							<th>Forma de Pago</th>
							<th>Fecha</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td rowspan="3">
								<p>{{$cotizacion->cliente->name}}</p>
							</td>
							<td>{{$cotizacion->waytopay}}</td>
							<td> {{$cotizacion->created_at->format('M-d-Y')}}</td>
						</tr>
						<tr class="table-primary">
							<th>Vendedor</th>
							<th>Vencimiento</th>
						</tr>
						<tr>
							<td>{{$cotizacion->seller->name}}</td>
							<td>{{$cotizacion->fecha_vencimiento->format('M-d-Y')}}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!--otra fila-->
		<div class="row">
			<div class="col-sm-12">
				<table class="table table-striped table-sm">
					<thead>
						<tr>
							<th>Producto</th>
							<th>Código</th>
							<th>Precio</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($cotizacion->products as $item)
						<tr>
							<td>{{$item->name}}</td>
							<td>{{$item->cod}}</td>	
							<td>{{$empresa->moneda}}{{$item->price}}</td>
						</tr>	
						@endforeach
						<tr>
							<th></th>
							<th>Sub-Total</th>
							<td>{{$empresa->moneda}}{{$cotizacion->subtotal}}</td>
						</tr>
						<tr>
								<th></th>
								<th>ITBMS</th>
								<td>{{$empresa->moneda}}{{$cotizacion->itbms}}</td>
							</tr>
						<tr>
								<th></th>
								<th>Total</th>
								<td>{{$empresa->moneda}}{{$cotizacion->total}}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

</body>
</html>