routes/web.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

Route::resource('clientes', 'ClientController')->middleware('auth');

Route::resource('productos', 'ProductController')->middleware('auth');

Route::resource('cotizaciones', 'QuotationController')->middleware('auth');

Route::resource('roles', 'RoleController')->middleware('auth');

Route::get('agregarproductos/{id}', 'AddProductQuotation@add')->name('addproduct')->middleware('auth');
Route::get('forvue/{id}', 'AddProductQuotation@useByVue')->middleware('auth');
Route::post('agregarproductos/{id}', 'AddProductQuotation@store')->name('storeproduct')->middleware('auth');
Route::post('quitarproductos/{id}', 'AddProductQuotation@delete')->name('deleteproduct')->middleware('auth');




//rutas de configuracion de sistema 

Route::get('configuracion', 'ConfigController@index')->name('configuracion.index')->middleware('auth');
Route::get('configuracion/{empresa}', 'ConfigController@edit')->name('configuracion.edit')->middleware('auth');
Route::put('configuracion/{empresa}', 'ConfigController@update')->name('configuracion.update')->middleware('auth');

//usuarios del sistema
Route::get('perfil/{id}', 'UserController@perfil')->name('perfil')->middleware('auth');
Route::get('usuarios', 'UserController@index')->name('usuarios.index')->middleware('auth', 'permission:usuarios.index');
Route::get('usuarios/create', 'UserController@create')->name('usuarios.create')->middleware('auth');
Route::post('usuarios', 'UserController@store')->name('usuarios.store')->middleware('auth');
Route::get('usuarios/{id}/edit', 'UserController@edit')->name('usuarios.edit')->middleware('auth');
Route::put('usuarios/{id}', 'UserController@update')->name('usuarios.update')->middleware('auth');
Route::delete('usuarios/{id}', 'UserController@delete')->name('usuarios.delete')->middleware('auth');
//cambiar contraseña
Route::get('usuarios/{id}/cambiar-contraseña', 'UserController@editPass')->name('edit.password')->middleware('auth');
Route::put('usuarios-update/{id}', 'UserController@updatePass')->name('update.password')->middleware('auth');


Route::get('empresa', 'RecursosAccesibles@getData');

Route::get('addproductsvue/{id}', 'AddProductQuotation@getProducts');

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
        return view('roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permisos = Permission::all();
        return view('roles.create', compact('permisos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $role = Role::create(['name' => $request->name]);

        $role->givePermissionTo($request->permission_id);

        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::findOrFail($id);
        $permisos = Permission::all();
        return view('roles.edit', compact('role', 'permisos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request->permission_id);
        $role = Role::findOrFail($id);

        $role->update(['name' => $request->name]);

        $role->permissions()->sync($request->permission_id);

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);

        $role->permissions()->detach();

        $role->delete();
        
        return back();
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                        Nuevo Role
                    </div>
                </div>
                
                <div class="card-body">
                    <form action="{{route('roles.store')}}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="textinput">Nombre</label>  
                            <div class="col-md-12">
                                    <input type="text" name="name" class="form-control input-md">
                                    
                            </div>
                        </div>

                       
                        <div class="container">
                            <div class="row">
                                
                                <div class="col-sm-3">
                                        <h4>Módulo Clientes</h4>
                                    <!--Módulo Clientes-->
                                    @foreach ($permisos as $permiso)
                                        @if ($permiso->name == 'clientes.index' | 
                                                $permiso->name == 'clientes.show' | 
                                                $permiso->name == 'clientes.create'|
                                                $permiso->name == 'clientes.edit'  |
                                                $permiso->name == 'clientes.destroy')
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}">
                                            <label class="form-check-label" for="{{$permiso->id}}">
                                                {{$permiso->description}}
                                            </label>
                                    </div> 
                                        @endif
                                     @endforeach
                                     
                                </div>
                                <!--Módulo Productos-->
                                <div class="col-sm-3">
                                        <h4>Módulo Productos</h4>
                                        <!--Módulo Productos-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'productos.index' | 
                                                    $permiso->name == 'productos.create'|
                                                    $permiso->name == 'productos.store' |
                                                    $permiso->name == 'productos.edit'  |
                                                    $permiso->name == 'productos.update'|
                                                    $permiso->name == 'productos.destroy')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}">
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         <!--Módulo -->
                                    </div>
                                    <!--Módulo Productos-->
                                <div class="col-sm-3">
                                        <h4>Módulo Cotizaciones</h4>
                                        <!--Módulo Cotizaciones-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'cotizaciones.index' | 
                                                    $permiso->name == 'cotizaciones.create'|
                                                    $permiso->name == 'cotizaciones.store' |
                                                    $permiso->name == 'cotizaciones.edit'  |
                                                    $permiso->name == 'cotizaciones.update'|
                                                    $permiso->name == 'cotizaciones.destroy')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}">
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         <!--Módulo -->
                                </div>
                                <div class="col-sm-3">
                                        <h4>Módulo Usuarios</h4>
                                        <!--Módulo Usuarios-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'usuarios.index' | 
                                                    $permiso->name == 'usuarios.create'|
                                                    $permiso->name == 'usuarios.store' |
                                                    $permiso->name == 'usuarios.edit'  |
                                                    $permiso->name == 'usuarios.update'|
                                                    $permiso->name == 'usuarios.delete')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}">
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         <!--Módulo -->
                                </div>
                                <hr>
                                <br>
                                
                            </div>
                        </div>   
                        <hr>
                        <div class="container">
                                <div class="row">
                                    
                                    <div class="col-sm-3">
                                            <h4>Módulo Agregar Productos(Cotización)</h4>
                                        <!--Módulo Clientes-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'addproduct' | 
                                                    $permiso->name == 'storeproduct'|
                                                    $permiso->name == 'deleteproduct'|
                                                    $permiso->name == 'generar.cotizacion')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}">
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         
                                    </div>

                                    <div class="col-sm-3">
                                            <h4>Módulo Configuración Empresa</h4>
                                        <!--Módulo Clientes-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'configuracion.index' | 
                                                    $permiso->name == 'configuracion.update'|
                                                    $permiso->name == 'configuracion.edit')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}">
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         
                                    </div>

                                    <div class="col-sm-3">
                                            <h4>Módulo Contraseñas</h4>
                                        <!--Módulo Clientes-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'edit.password' | 
                                                    $permiso->name == 'update.password')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}">
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         
                                    </div>

                                </div>
                            </div> 
                        <hr>
                        <!-- Button -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for=""></label>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary">Guardar</button>
                        </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                            <a href="{{route('roles.index')}}" class="btn btn-primary btn-sm">
                                    <i class="fa fa-arrow-left" aria-hidden="true"></i>
                                </a>
                        Editar Role
                    </div>
                </div>
                
                <div class="card-body">
                    <form action="{{route('roles.update', $role->id)}}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="textinput">Nombre</label>  
                            <div class="col-md-12">
                                    <input type="text" name="name" class="form-control input-md" value="{{$role->name}}">
                                    
                            </div>
                        </div>
                     
                        <div class="container">
                            <div class="row">
                                
                                <div class="col-sm-3">
                                        <h4>Módulo Clientes</h4>
                                    <!--Módulo Clientes-->
                                    @foreach ($permisos as $permiso)
                                        @if ($permiso->name == 'clientes.index' | 
                                                $permiso->name == 'clientes.show' | 
                                                $permiso->name == 'clientes.create'|
                                                $permiso->name == 'clientes.edit'  |
                                                $permiso->name == 'clientes.destroy')
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}" {{ $role->permissions->pluck('id')->contains($permiso->id) ? 'checked' : ''}}>
                                            <label class="form-check-label" for="{{$permiso->id}}">
                                                {{$permiso->description}}
                                            </label>
                                    </div> 
                                        @endif
                                     @endforeach
                                     
                                </div>
                                <!--Módulo Productos-->
                                <div class="col-sm-3">
                                        <h4>Módulo Productos</h4>
                                        <!--Módulo Productos-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'productos.index' | 
                                                    $permiso->name == 'productos.create'|
                                                    $permiso->name == 'productos.store' |
                                                    $permiso->name == 'productos.edit'  |
                                                    $permiso->name == 'productos.update'|
                                                    $permiso->name == 'productos.destroy')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}" {{ $role->permissions->pluck('id')->contains($permiso->id) ? 'checked' : ''}}>
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         <!--Módulo -->
                                    </div>
                                    <!--Módulo Productos-->
                                <div class="col-sm-3">
                                        <h4>Módulo Cotizaciones</h4>
                                        <!--Módulo Cotizaciones-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'cotizaciones.index' | 
                                                    $permiso->name == 'cotizaciones.create'|
                                                    $permiso->name == 'cotizaciones.store' |
                                                    $permiso->name == 'cotizaciones.edit'  |
                                                    $permiso->name == 'cotizaciones.update'|
                                                    $permiso->name == 'addproduct'|
                                                    $permiso->name == 'cotizaciones.destroy')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}" {{ $role->permissions->pluck('id')->contains($permiso->id) ? 'checked' : ''}}>
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         <!--Módulo -->
                                </div>
                                <div class="col-sm-3">
                                        <h4>Módulo Usuarios</h4>
                                        <!--Módulo Usuarios-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'usuarios.index' | 
                                                    $permiso->name == 'usuarios.create'|
                                                    $permiso->name == 'usuarios.store' |
                                                    $permiso->name == 'usuarios.edit'  |
                                                    $permiso->name == 'usuarios.update'|
                                                    $permiso->name == 'usuarios.delete')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}" {{ $role->permissions->pluck('id')->contains($permiso->id) ? 'checked' : ''}}>
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         <!--Módulo -->
                                </div>
                                <hr>
                                <br>
                                
                            </div>
                        </div>   
                        <hr>
                        <div class="container">
                                <div class="row">
                                    
                                    <div class="col-sm-3">
                                            <h4>Módulo Configuración Empresa</h4>
                                        <!--Módulo Clientes-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'configuracion.index' | 
                                                    $permiso->name == 'configuracion.update'|
                                                    $permiso->name == 'configuracion.edit')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}" {{ $role->permissions->pluck('id')->contains($permiso->id) ? 'checked' : ''}}>
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         
                                    </div>

                                    <div class="col-sm-3">
                                            <h4>Módulo Contraseñas</h4>
                                        <!--Módulo Clientes-->
                                        @foreach ($permisos as $permiso)
                                            @if ($permiso->name == 'edit.password' | 
                                                    $permiso->name == 'update.password')
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="permission_id[]" value="{{$permiso->id}}" id="{{$permiso->id}}" {{ $role->permissions->pluck('id')->contains($permiso->id) ? 'checked' : ''}}>
                                                <label class="form-check-label" for="{{$permiso->id}}">
                                                    {{$permiso->description}}
                                                </label>
                                        </div> 
                                            @endif
                                         @endforeach
                                         
                                    </div>

                                </div>
                            </div> 
                        <hr>
                        
                        <!-- Button -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for=""></label>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                        </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="borde">
                    <div class="card-header">
                        Roles
                        <a href="{{route('roles.create')}}" class="btn btn-primary btn-sm float-right">
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
                
                <div class="card-body">
                   <div class="table-responsive">
                        <table class="table tabla-hover table-sm">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nombre</th>
                                    <th>Guard</th>
                                    <th>Editar</th>
                                    <th><center>Eliminar</center></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($roles as $role)
                                    <tr>
                                        <td>{{$role->id}}</td>
                                        <td>{{$role->name}}</td>
                                        <td>{{$role->guard_name}}</td>
                                        <td>
                                            <a href="{{route('roles.edit', $role->id)}}" class="btn btn-warning btn-sm">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </a>
                                        </td>
                                        <td>
                                            <center>
                                                <form action="{{route('roles.destroy', $role->id)}}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('¿Estas Seguro de eliminar el role?')">
                                                            <i class="fa fa-window-close" aria-hidden="true"></i>
                                                    </button>
                                                </form>
                                                </center>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                   </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection